name: CI/CD Pipeline
on:
  push:
    branches: [main]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/main'
    steps:
      # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAVIIDJL5ULUN4EY2S
          aws-secret-access-key: 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
          aws-region: ap-southeast-1
      # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name Earley-Dev \
            --deployment-group-name EarleyDev-DepGrp \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository= tendau/Earley-Dev, commitId=${{ github.sha }}
